changesetIgnorePatterns:
  - .github/**
  - .vscode/**
  - .yarn/cache/**

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableImmutableInstalls: false

lockfileFilename: yarn.lock

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs
